version: '3.5'
volumes:
  sdforge:
    driver: local
    driver_opts:
      type: none
      device: /path/to/docker/sdforge
      o: bind
services:
  sdforge:
    container_name: sdforge
    image: lolumi/sdforgeui:1.0.0
    ports:
      - 7860:7860
    build:
      context: .
    volumes:
      - sdforge:/stable-diffusion-webui-forge
    command: --listen
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    restart: unless-stopped
